import fonts from '@/app/fonts'
import './globals.css'
import './style.css'

export const metadata = {
  title: 'Traffico',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={fonts.rubik.className}>{children}</body>
    </html>
  )
}
